.TH SEDAM 1
.SH NAME
sedam \- stream interface to edam
.SH SYNOPSIS
.B sedam
[
.B -n
]
[
.B -e
.I script
]
[
.B -f
.I sfile
]
[
.B --
]
[
.I file ...
]
.SH DESCRIPTION
.I Sedam
copies the named
.I files
(standard input default) to the standard output, edited by a script of
.IR edam
commands (q.v.).
When the script starts, the entire input is selected.
The
.B -f
option causes the script to be taken from file
.IR sfile .
If there is a
.B -e
option and no
.BR -f ,
the flag
.B -e
may be omitted. 
The
.B -n
option suppresses the default output.
The
.B --
option signals the end of the commandline options. All following arguments
are filenames.
.ne 4
.SH EXAMPLES
.TP
.B sedam -n ,10p file
Print first 10 lines of file.
.TP
.B sedam 'y/[a-zA-Z]+/ c/\en/' *.ms
Print one word per line.
.TP
.B sedam 's/\en\en+/\en/g'
Delete empty lines from standard input.
.TP
.B sedam 's/UNIX/& system/g'
Replace every instance of 
.L UNIX
by
.LR "UNIX system" .
.TP
.B sedam 'y/[a-zA-Z]+/ c/\en/' | grep . | sort | uniq -c
Count frequency of words read from standard input.
.SH SEE ALSO
.IR sed (1), 
.MR edam (1) ,
.MR regexp (7)
.PP
Rob Pike,
``The text editor sam''.
.SH BUGS
Sedam consumes all of standard input before running the script.
